//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnection) DeepCopyInto(out *SDKConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnection.
func (in *SDKConnection) DeepCopy() *SDKConnection {
	if in == nil {
		return nil
	}
	out := new(SDKConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SDKConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnectionInitParameters) DeepCopyInto(out *SDKConnectionInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SDKVersion != nil {
		in, out := &in.SDKVersion, &out.SDKVersion
		*out = new(string)
		**out = **in
	}
	if in.EncryptPayload != nil {
		in, out := &in.EncryptPayload, &out.EncryptPayload
		*out = new(bool)
		**out = **in
	}
	if in.IncludeVisualExperiments != nil {
		in, out := &in.IncludeVisualExperiments, &out.IncludeVisualExperiments
		*out = new(bool)
		**out = **in
	}
	if in.IncludeDraftExperiments != nil {
		in, out := &in.IncludeDraftExperiments, &out.IncludeDraftExperiments
		*out = new(bool)
		**out = **in
	}
	if in.IncludeDraftExperimentRefs != nil {
		in, out := &in.IncludeDraftExperimentRefs, &out.IncludeDraftExperimentRefs
		*out = new(bool)
		**out = **in
	}
	if in.IncludeExperimentNames != nil {
		in, out := &in.IncludeExperimentNames, &out.IncludeExperimentNames
		*out = new(bool)
		**out = **in
	}
	if in.IncludeRedirectExperiments != nil {
		in, out := &in.IncludeRedirectExperiments, &out.IncludeRedirectExperiments
		*out = new(bool)
		**out = **in
	}
	if in.IncludeRuleIds != nil {
		in, out := &in.IncludeRuleIds, &out.IncludeRuleIds
		*out = new(bool)
		**out = **in
	}
	if in.IncludeProjectIdInMetadata != nil {
		in, out := &in.IncludeProjectIdInMetadata, &out.IncludeProjectIdInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.IncludeCustomFieldsInMetadata != nil {
		in, out := &in.IncludeCustomFieldsInMetadata, &out.IncludeCustomFieldsInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.AllowedCustomFieldsInMetadata != nil {
		in, out := &in.AllowedCustomFieldsInMetadata, &out.AllowedCustomFieldsInMetadata
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeTagsInMetadata != nil {
		in, out := &in.IncludeTagsInMetadata, &out.IncludeTagsInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.IncludeExperimentScheduleInMetadata != nil {
		in, out := &in.IncludeExperimentScheduleInMetadata, &out.IncludeExperimentScheduleInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.ProxyEnabled != nil {
		in, out := &in.ProxyEnabled, &out.ProxyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyHost != nil {
		in, out := &in.ProxyHost, &out.ProxyHost
		*out = new(string)
		**out = **in
	}
	if in.HashSecureAttributes != nil {
		in, out := &in.HashSecureAttributes, &out.HashSecureAttributes
		*out = new(bool)
		**out = **in
	}
	if in.RemoteEvalEnabled != nil {
		in, out := &in.RemoteEvalEnabled, &out.RemoteEvalEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SavedGroupReferencesEnabled != nil {
		in, out := &in.SavedGroupReferencesEnabled, &out.SavedGroupReferencesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncludeReferencedPrerequisites != nil {
		in, out := &in.IncludeReferencedPrerequisites, &out.IncludeReferencedPrerequisites
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnectionInitParameters.
func (in *SDKConnectionInitParameters) DeepCopy() *SDKConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(SDKConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnectionList) DeepCopyInto(out *SDKConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SDKConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnectionList.
func (in *SDKConnectionList) DeepCopy() *SDKConnectionList {
	if in == nil {
		return nil
	}
	out := new(SDKConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SDKConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnectionObservation) DeepCopyInto(out *SDKConnectionObservation) {
	*out = *in
	if in.Languages != nil {
		in, out := &in.Languages, &out.Languages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Connected != nil {
		in, out := &in.Connected, &out.Connected
		*out = new(bool)
		**out = **in
	}
	if in.SSEEnabled != nil {
		in, out := &in.SSEEnabled, &out.SSEEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnectionObservation.
func (in *SDKConnectionObservation) DeepCopy() *SDKConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(SDKConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnectionParameters) DeepCopyInto(out *SDKConnectionParameters) {
	*out = *in
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SDKVersion != nil {
		in, out := &in.SDKVersion, &out.SDKVersion
		*out = new(string)
		**out = **in
	}
	if in.EncryptPayload != nil {
		in, out := &in.EncryptPayload, &out.EncryptPayload
		*out = new(bool)
		**out = **in
	}
	if in.IncludeVisualExperiments != nil {
		in, out := &in.IncludeVisualExperiments, &out.IncludeVisualExperiments
		*out = new(bool)
		**out = **in
	}
	if in.IncludeDraftExperiments != nil {
		in, out := &in.IncludeDraftExperiments, &out.IncludeDraftExperiments
		*out = new(bool)
		**out = **in
	}
	if in.IncludeDraftExperimentRefs != nil {
		in, out := &in.IncludeDraftExperimentRefs, &out.IncludeDraftExperimentRefs
		*out = new(bool)
		**out = **in
	}
	if in.IncludeExperimentNames != nil {
		in, out := &in.IncludeExperimentNames, &out.IncludeExperimentNames
		*out = new(bool)
		**out = **in
	}
	if in.IncludeRedirectExperiments != nil {
		in, out := &in.IncludeRedirectExperiments, &out.IncludeRedirectExperiments
		*out = new(bool)
		**out = **in
	}
	if in.IncludeRuleIds != nil {
		in, out := &in.IncludeRuleIds, &out.IncludeRuleIds
		*out = new(bool)
		**out = **in
	}
	if in.IncludeProjectIdInMetadata != nil {
		in, out := &in.IncludeProjectIdInMetadata, &out.IncludeProjectIdInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.IncludeCustomFieldsInMetadata != nil {
		in, out := &in.IncludeCustomFieldsInMetadata, &out.IncludeCustomFieldsInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.AllowedCustomFieldsInMetadata != nil {
		in, out := &in.AllowedCustomFieldsInMetadata, &out.AllowedCustomFieldsInMetadata
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeTagsInMetadata != nil {
		in, out := &in.IncludeTagsInMetadata, &out.IncludeTagsInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.IncludeExperimentScheduleInMetadata != nil {
		in, out := &in.IncludeExperimentScheduleInMetadata, &out.IncludeExperimentScheduleInMetadata
		*out = new(bool)
		**out = **in
	}
	if in.ProxyEnabled != nil {
		in, out := &in.ProxyEnabled, &out.ProxyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyHost != nil {
		in, out := &in.ProxyHost, &out.ProxyHost
		*out = new(string)
		**out = **in
	}
	if in.HashSecureAttributes != nil {
		in, out := &in.HashSecureAttributes, &out.HashSecureAttributes
		*out = new(bool)
		**out = **in
	}
	if in.RemoteEvalEnabled != nil {
		in, out := &in.RemoteEvalEnabled, &out.RemoteEvalEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SavedGroupReferencesEnabled != nil {
		in, out := &in.SavedGroupReferencesEnabled, &out.SavedGroupReferencesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncludeReferencedPrerequisites != nil {
		in, out := &in.IncludeReferencedPrerequisites, &out.IncludeReferencedPrerequisites
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnectionParameters.
func (in *SDKConnectionParameters) DeepCopy() *SDKConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(SDKConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnectionSpec) DeepCopyInto(out *SDKConnectionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnectionSpec.
func (in *SDKConnectionSpec) DeepCopy() *SDKConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SDKConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConnectionStatus) DeepCopyInto(out *SDKConnectionStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConnectionStatus.
func (in *SDKConnectionStatus) DeepCopy() *SDKConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(SDKConnectionStatus)
	in.DeepCopyInto(out)
	return out
}
